---
title: "Exam2022"
author: "tfd199, lhb642, tgx333"
date: "6/11/2022"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(RSQLite)
library(tidyverse)
library(tidymodels) 
library(furrr) 
library(glmnet)
library(broom)
library(timetk)
library(scales)
library(lubridate)
library(scales)
library(frenchdata)
library(caret)
library(ggplot2)
library(ggpubr)
library(kableExtra)
library(mltools)
library(data.table)
library(vtable)
library(keras)
library(quadprog)
library(rmgarch)
library(xts)
```


### 1.
**Use the data until December 31, 2015 to estimate the parameters of the Fama French 3-factor model.**

```{r}
#Loading in the CSV file
data <- read_csv("data/data_exam2022.csv") %>%
  filter(month < "2016-01-01") %>% drop_na()

#Estimation:
coefficients <- matrix(NA,
                             nrow = nrow(unique(data['permno'])),
                             ncol = 5) 

colnames(coefficients) = c("Permno","Alpha","mkt_excess","smb","hml")

for (i in 1:8) {
  
  
  t =  unique(data['permno'])[i,]
  coefficients[i,2:5] <- lm(ret_excess ~ mkt_excess + smb + hml, 
     data = data %>% filter(permno == t[[1]] )) %>% coefficients()
  
  coefficients[i,1] <- t[[1]]
}

coefficients %>% kbl(caption = "Summary of Fama-French 3 Factor model regression coefficients",digits = 4) %>%
  kable_classic(full_width = F, html_font = "Cambria")

```

